server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sbbeetl?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: localhost
        port: 6379

beetl:
    suffix: html
    beetlsql.dev: true

beetlsql:
    basePackage: com.wang.dao

logging:
    level.com.wang: debug